version: 2

sources:
  - name: DEVELOPER_DB
    description: <markdown_string>
    database: DEVELOPER_DB
    schema: VIVEKKETHA_SCHEMA
    tables:
      - name: ACCOUNT
      - name: CAMPAIGN
      - name: CASE
      - name: CONTACT
      - name: CONTRACT
      - name: LEAD
      - name: OPPORTUNITY
      - name: ORDER
      - name: PRODUCT_2